### PR TITLE
WIP: add the linestyles option for implicants drawing

### LINKED ISSUE #16: FeatureRequest: colour-blind compatible way to visually differentiate between implicants
This package produces beautiful visuals for karnaugh maps and the automatic colors for implicants greatly help learners with identification, especially for maps with more than 4 inputs, I use it to make corrections for my lessons.

I just realized though this approach won't work for colour-blind people, maybe we can make the outline of the implicants use different line styles (dotted, dashed, waved, …)?

### PR DESCRIPTION
**Pull request by Dettorer**
Closes #16

### CODE REVIEW

**Comment by 2pi** [comment]
How would you like to be attributed? Would this be okay? 

> [Dettorer](https://github.com/Dettorer)

**Comment by Dettorer** [comment]
That's really nice of you to ask, I'd like [Paul Hervot](https://github.com/Dettorer) please.

**Comment by 2pi** [comment]
Great thanks! I've skimmed through the PR and it looks good in general. See my comment in the original issue for now.

I'm really happy that you added test cases! :star2: Thank you!

**Comment by 2pi** [comment]
I've added attribution as discussed above. Regarding licensing. Similarly to https://github.com/2pi/karnaugh-map/pull/7#issuecomment-277514055 I just want to check that you are aware and okay with the licensing([CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/)).

**Comment by Dettorer** [comment]
I forgot to answer your last question too, sorry. I'm totally ok with the current licensing.

**Comment by Dettorer** [comment]
Thanks for the proofread and extra test! Do you want me to do anything else with this PR?

**Comment by 2pi** [comment]
Perfect! No I don't think so.

Thank you very much!

**Pull request merged**
