### PR TITLE
Added support for terms command

### PR DESCRIPTION
**Pull request by oscargus**
Replaces #6 by introducing `\terms{cells}{content}`. 

`\minterms`, `\maxterms`, and `\indeterminants` now use `\terms` underneath. 

An example is also added to the manual, but due to a line break, it does not look so good.

No explicit tests (although I got slightly longer in the test now, diff-pdf was missing and I'm currently not in the situation to be able install it properly).

### CODE REVIEW

**Comment by 2pi** [comment]
Thank you very much!

I've fixed some indentations, added some test cases and fixed the documentation issues.

~~Before I merge I would just like to make sure that your contributions (and possible future contributions) to karnaugh-map are under [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) as the rest of the codebase?~~ Oh wait, it's a ShareAlike license, hence (according to my interpretation) you must release it under the same license if you release any modifications to karnaugh-map!? Right? I probably should have emphasized this earlier! Sorry!

Anyway would adding

> Contributors include [Oscar Gustafsson](https://github.com/oscargus).

to the end of https://github.com/2pi/karnaugh-map/blob/master/README.md#license suffice as attribution? And therefore changing the top part of the karnaugh-map.dtx file similarly. Finally changing the copyright line to

> Copyright (C) 2015 Mattias Jacobsson and contributors

**Comment by oscargus** [comment]
I am open to any solution regarding license and acknowledgement. While not fully understanding (going into details) the license issue, trusting you fully there, I think your acknowledgement suggestion sounds just fine.

Maybe updating the copyright year?

**Comment by 2pi** [comment]
Great, thanks! To be honest I've a hard time understanding it myself, this is the main reason the initial release was delayed about a year. However to my understanding this is how it supposed to work.

I'll fix the year too.

**Comment by 2pi** [comment]
Thanks for your contribution :+1:

**Pull request merged**
